export const SET_FORM_TITLE = 'SET_FORM_TITLE'
export const SET_CONFIGURATION_PANEL_MODE = 'SET_CONFIGURATION_PANEL_MODE'
export const ADD_FORM_ELEMENT = 'ADD_FORM_ELEMENT'
export const REMOVE_FORM_ELEMENT = 'REMOVE_FORM_ELEMENT'
