export const SET_FORM_TITLE = 'SET_FORM_TITLE'
export const SET_CONFIGURATION_PANEL_MODE = 'SET_CONFIGURATION_PANEL_MODE'
export const ADD_FORM_GROUP = 'ADD_FORM_GROUP'
export const REMOVE_FORM_GROUP = 'REMOVE_FORM_GROUP'
